In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
%matplotlib inline

In [2]:
import csv

txt_file = r"C:\\Users\\naman\\Desktop\\data_banknote_authentication.txt"
csv_file = r"C:\\Users\\naman\\Desktop\\data.csv"

in_txt = csv.reader(open(txt_file,"rt"),delimiter=',')
out_csv = csv.writer(open(csv_file,"wt"))

out_csv.writerows(in_txt)

In [3]:
cols = ['variance','skewness','kurtosis','entropy','class']

In [5]:
df = pd.read_csv("C:\\Users\\naman\\Desktop\\data.csv",names=cols)

In [6]:
df.head()

variance  skewness  kurtosis  entropy  class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1182 entries, 0 to 1181
Data columns (total 5 columns):
variance    1182 non-null float64
skewness    1182 non-null float64
kurtosis    1182 non-null float64
entropy     1182 non-null float64
class       1182 non-null int64
dtypes: float64(4), int64(1)
memory usage: 46.2 KB


In [8]:
df['class'].unique()

array([0, 1], dtype=int64)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()

In [15]:
scaler.fit(df.drop(['class'],axis=1))

StandardScaler(copy=True, with_mean=True, with_std=True)

In [16]:
features = scaler.transform(df.drop('class',axis=1))

In [17]:
features

array([[ 1.00978563,  1.08277913, -0.99198003,  0.33873404],
       [ 1.34614925,  0.99663534, -0.90679754, -0.14501881],
       [ 1.09872566, -0.86990571,  0.16385861,  0.60247706],
       ..., 
       [-1.50098704, -0.10285109, -0.26210268, -0.58868886],
       [-1.11542255, -0.63078629,  0.42631936,  0.72510822],
       [-1.61441833, -1.5494001 ,  2.26493704,  0.47368408]])

In [18]:
features[0]

array([ 1.00978563,  1.08277913, -0.99198003,  0.33873404])

In [19]:
y = df['class']

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [69]:
model = KNeighborsClassifier(n_neighbors=100)

In [70]:
x_train,x_test,y_train,y_test = train_test_split(features,y)

In [71]:
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=100, p=2,
           weights='uniform')

In [72]:
model.score(x_test,y_test)

0.94256756756756754

In [73]:
from sklearn.metrics import confusion_matrix

In [74]:
pred = model.predict(x_test)

In [75]:
confusion_matrix(y_test,pred)

array([[189,   6],
       [ 11,  90]], dtype=int64)

In [77]:
from sklearn.metrics import classification_report

In [78]:
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.94      0.97      0.96       195
          1       0.94      0.89      0.91       101

avg / total       0.94      0.94      0.94       296

